# Generated by Django 5.2.1 on 2025-05-23 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=100)),
                ('endereco', models.TextField(max_length=250)),
                ('capacidade_m3', models.FloatField(default=0)),
                ('modelo', models.CharField(choices=[('P', 'Própio'), ('T', 'Terceirizado'), ('H', 'Híbrido')], default='P', max_length=1)),
                ('tipo', models.CharField(choices=[('S', 'Silo'), ('T', 'Tanque'), ('R', 'Rack'), ('P', 'Porta-palete'), ('F', 'Flow-rack'), ('E', 'Estante'), ('D', 'Divisorias'), ('O', 'Outro')], default='E', max_length=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'depositos',
            },
        ),
    ]
