# Generated by Django 5.2.1 on 2025-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deposito_status_alter_deposito_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='public/uploads/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.FloatField(blank=True, db_comment='Peso em Kg', null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('UN', 'Unidade'), ('MG', 'Miligrama'), ('G', 'Grama'), ('KG', 'Quilograma'), ('L', 'Litro'), ('ML', 'mililitros'), ('M', 'metro'), ('M3', 'volume')], max_length=2),
        ),
    ]
