# Generated by Django 5.2.1 on 2025-05-23 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produto_fotografia_alter_produto_peso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='qtd_embalagem',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Água', 'Água'), ('Alimento', 'Alimento'), ('Bebida', 'Bebida'), ('Ferramenta', 'Ferramenta'), ('Gás', 'Gás'), ('Higiene', 'Higiene'), ('Informática', 'Informática'), ('Limpeza', 'Limpeza'), ('Papelaria', 'Papelaria'), ('Tabaco', 'Tabaco'), ('Outros', 'Outros')], default='Outros', max_length=15),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('MG', 'Miligrama'), ('G', 'Grama'), ('KG', 'Quilograma'), ('L', 'Litro'), ('ML', 'Mililitros'), ('M', 'Metro'), ('M3', 'Volume')], max_length=2),
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.FloatField(default=1)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1)),
                ('nome_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.deposito')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimentacoes',
            },
        ),
    ]
