# Generated by Django 5.2.1 on 2025-05-25 19:21

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produto_marca_produto_qtd_embalagem_produto_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_path_and_rename),
        ),
    ]
