# Generated by Django 5.2.1 on 2025-05-26 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_produto_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.produto'),
        ),
    ]
