# Generated by Django 5.2.1 on 2025-05-26 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movimentacao_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto'),
        ),
    ]
