# Generated by Django 5.2.1 on 2025-05-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_movimentacao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
